config/routes.rb
Rails.application.routes.draw do

  get 'units/dashboard/:responsible', :to => 'dashboard#index'

  resources :units do
    resources :steps, only: [:index, :show] do
      resources :movements
    end
  end

  root 'units#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/movement.rb
class Movement < ApplicationRecord
  
  belongs_to :step
  belongs_to :flow

  serialize :details, Hash

  after_create_commit :perform_system_step,  if: -> {step_is_open? && step_is_system?}
  after_create_commit :evaluate_opening_next_step, if: -> {last_step_is_closed? && step_is_closed?}

  after_create_commit :print_shit

  def print_shit
    #puts "Unit is #{self.unit_is_open?} and Step is #{self.step_is_open?}. System is System? #{self.step_is_system?}"
  end

  def evaluate_opening_next_step
    open_next_step(self.step.unit, Flow.find(self.step.closed_with.flow_id).children.first)
  end

  def perform_system_step
    puts ">> Is System Step"
    if self.flow_id == 800001
      if self.step.unit.serialised?
        @close_with = 850001 #Unit is serialised. Evaluating Open Orders
      else
        @close_with = 850002 #Unit is NOT serialised. Directing flow
      end 
    elsif self.flow_id == 800002
      puts ">> Is 800002"
      details = Movement.where("id < #{self.id}").where(flow_id: 450001).last.details
      if details['average_repair_cost_YTD_above_65%_of_catalog_price'].to_i == 1 || details['average_purchase_cost_YTD_above_85%_of_catalog_price'].to_i == 1
        puts ">> Repair is not Feasible"
        @close_with = 850006 #Repair NOT feasible. Directing Flow
      else
        puts ">> Repair is Feasible"
        @close_with = 850004
        # to be written
      end
    else
      return false
    end  
    puts ">> Writing..."
    close_step(self.step, Flow.find(@close_with))
  end

  def step_is_system?
    if self.flow.side == "system" then true else false end
  end

  def step_is_closed?
    self.step.closed?
  end

  def step_is_open?
    !self.step_is_closed?
  end

  def last_step_is_closed?
    self.step.unit.steps.last.closed?
  end

  def last_step_is_open?
    !last_step_is_closed?
  end

  protected

  def open_next_step(unit, next_step)
    step = unit.steps.build(expires_at: Time.current + next_step.sla.to_i * 60).movements.build(flow_id: next_step.id)
    if step.save
      update_unit_parameters(unit)
    end
  end

  def update_unit_parameters(unit)
    unit.open = true
    unit.responsible = unit.steps.last.responsible.downcase
    unit.expires_at = unit.steps.last.expires_at
    unit.save
  end

  def close_step(step, flow)
    movement = step.movements.build(flow_id: flow.id)
    movement.save
  end

end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_action :set_movement, only: [:show, :edit, :update, :destroy]
  before_action :set_unit, :set_step

  # GET /movements
  # GET /movements.json
  def index
    @movements = Movement.all
  end

  # GET /movements/1
  # GET /movements/1.json
  def show
  end

  # GET /movements/new
  def new
    @movement = @step.movements.build
  end

  # GET /movements/1/edit
  def edit
  end

  # POST /movements
  # POST /movements.json
  def create
    @movement = @step.movements.build(movement_params)

    respond_to do |format|
      if @movement.save
        format.html { redirect_to @unit, notice: 'Movement was successfully created.' }
        format.json { render :show, status: :created, location: @movement }
      else
        format.html { redirect_to @unit, notice: 'There was a problem creating the Movement.' }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movements/1
  # PATCH/PUT /movements/1.json
  def update
    respond_to do |format|
      if @movement.update(movement_params)
        format.html { redirect_to @movement, notice: 'Movement was successfully updated.' }
        format.json { render :show, status: :ok, location: @movement }
      else
        format.html { render :edit }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movements/1
  # DELETE /movements/1.json
  def destroy
    @movement.destroy
    respond_to do |format|
      format.html { redirect_to movements_url, notice: 'Movement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:unit_id])
    end

    def set_step
      @step = Step.find(params[:step_id])
    end

    def set_movement
      @movement = Movement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def set_approved_dynamic_params
      return ["remarks"] << MovementField.where(flow_id: params['movement']['flow_id']).pluck(:name)
    end
    
    def movement_params
      params.require(:movement).permit(:flow_id, details: set_approved_dynamic_params )
    end
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/views/movements/_form.html.erb
<%= form_with(model: movement, local: true) do |form| %>
  <% if movement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movement.errors.count, "error") %> prohibited this movement from being saved:</h2>

      <ul>
      <% movement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :step_uid %>
    <%= form.text_field :step_uid %>
  </div>

  <div class="field">
    <%= form.label :flow_id %>
    <%= form.text_field :flow_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movements/edit.html.erb
<h1>Editing Movement</h1>

<%= render 'form', movement: @movement %>

<%= link_to 'Show', @movement %> |
<%= link_to 'Back', movements_path %>

app/views/movements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movements</h1>

<table>
  <thead>
    <tr>
      <th>Step uid</th>
      <th>Flow</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movements.each do |movement| %>
      <tr>
        <td><%= movement.step_uid %></td>
        <td><%= movement.flow %></td>
        <td><%= link_to 'Show', movement %></td>
        <td><%= link_to 'Edit', edit_movement_path(movement) %></td>
        <td><%= link_to 'Destroy', movement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movement', new_movement_path %>

app/views/movements/new.html.erb
<h1>New Movement</h1>

<%= render 'form', movement: @movement %>

<%= link_to 'Back', movements_path %>

app/views/movements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Step uid:</strong>
  <%= @movement.step_uid %>
</p>

<p>
  <strong>Flow:</strong>
  <%= @movement.flow %>
</p>

<%= link_to 'Edit', edit_movement_path(@movement) %> |
<%= link_to 'Back', movements_path %>