config/routes.rb
Rails.application.routes.draw do

  get 'units/dashboard/:responsible', :to => 'dashboard#index'

  resources :units do
    resources :steps, only: [:index, :show] do
      resources :movements
    end
  end

  root 'units#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/unit.rb
class Unit < ApplicationRecord

    validates :part_number, presence: true
    validates_presence_of :serial_number, :if => :serialised?
    validates_absence_of :serial_number, :unless => :serialised?

    has_many :steps, dependent: :destroy
    has_many :movements, through: :steps
    
    accepts_nested_attributes_for :steps
    validates_presence_of :steps

    enum responsible: Flow.sides

    def closed?
        !self.open?
    end

    def expires_at
        self.steps.last.expires_at
    end

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
    @unit.steps.build.movements.build
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)
    @unit.steps.first.expires_at = Time.current + 30
    @unit.steps.first.movements.new([flow_id: 500001])    

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:part_number, :serialised, :serial_number, steps_attributes: [movements_attributes: [:flow_id]])
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_with(model: unit, local: true) do |form| %>
  <% if unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :part_number %>
    <%= form.text_field :part_number %>
  </div>

  <div class="field">
    <%= form.label :serialised %>
    <%= form.check_box :serialised %>
  </div>

  <div class="field">
    <%= form.label :serial_number %>
    <%= form.text_field :serial_number %>
  </div>
  <br>
  <fieldset>
    <legend>Movement</legend>
    <%= form.fields_for :steps do |step| %>
      <%= step.fields_for :movements do |movement| %>
        <%= movement.collection_select :flow_id, Flow.where(id: Flow.storage_starter_flows), :id, :title, prompt: true %>
      <% end %>
    <% end %>
  </fieldset>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Units</h1>

<table class="table table-sm">
  <thead>
    <tr>
      <th>Part number</th>
      <th>Serial number</th>
      <th>Status</th>
      <th>Responsible</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.part_number %></td>
        <td><%= if unit.serialised then unit.serial_number else "-" end %></td>
        <td><%= if unit.open? then "Open" else "Closed" end %></td>
        <td><%= unit.responsible  %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Part number:</strong>
  <%= @unit.part_number %>
</p>

<p>
  <strong>Serialised:</strong>
  <%= @unit.serialised %>
</p>

<p>
  <strong>Serial number:</strong>
  <%= @unit.serial_number %>
</p>

<hr>

<h3>Steps</h3>
<br>

<div class="row">
  <div class="timeline-centered">
    <% @unit.steps.reverse_each do |step| %>
      <% colour_class = if step.open? then "secondary" else "success" end%>
      <article class="timeline-entry" step-id="<%= step.id %>">
        <div class="timeline-entry-inner">
          <div class="timeline-icon bg-<%= unless step.responsible == "System" then colour_class else "secondary" end %>">
            <i class="fas fa-<%= step.icon %>"></i>
          </div>
          <div class="timeline-label">
            <div class="row">
              <div class="col-md-6">
                <% movements = step.movements.joins(:flow).order("flows.direction") %>
                <% if step.open? %>
                  <h3 movement-flow-id="<%= movements.last.flow_id %>"><%= movements.last.flow.title %></h3>
                <% else %>
                  <p class="font-weight-light"><%= movements.first.flow.title %> <i class="fas fa-level-down-alt"></i></p>
                  <h3><%= movements.last.flow.title %></h3>
                <% end %>
              </div>
              <div class="col-md-6">
                <strong>Responsible:</strong> <%= step.responsible %><br>
                <% if step.open? %>
                  <strong>Step Status:</strong> Open<br><strong>SLA Status:</strong>
                  <br>- Time for completion: <%= distance_of_time_in_words(0, movements.last.flow.sla * 60) %>
                <% if step.expired? %>
                  <br>- SLA Already Expired. <small>Opened at: <%= step.created_at.to_formatted_s(:short)  %></small>
                  <br>- Expired At: <%= step.expires_at.to_formatted_s(:short) %> <small><%= distance_of_time_in_words(step.expires_at, Time.current) %> ago</small>
                <% else %>
                  <br>- Inside SLA. <small>Opened at: <%= step.created_at.to_formatted_s(:short)  %></small>
                  <br>- Will Expire At: <%= step.expires_at.to_formatted_s(:short) %> <small><%= distance_of_time_in_words(step.expires_at, Time.current) %> from now</small>
                <% end %>
              <% else %>
                <strong>Step Status:</strong> Closed<br><strong>SLA Status:</strong>
                <% if step.expired? %>
                  <br>- SLA Expired. <small>Opened at: <%= step.created_at.to_formatted_s(:short)  %></small>
                  <br>- Expired At: <%= step.expires_at.to_formatted_s(:short) %> <small><%= distance_of_time_in_words(step.expires_at, step.closed_at) %> delayed</small>
                <% else %>
                  <br>- SLA Accomplished. <small>Opened at: <%= step.created_at.to_formatted_s(:short)  %></small>
                  <br>- Closed At: <%= step.closed_at.to_formatted_s(:short) %> <small><%= distance_of_time_in_words(step.expires_at, step.closed_at) %> earlier</small>                
                <% end %>              
              <% end %>
            </div>
          </div>
          <br>
          <%= render "movements/descriptions/#{movements.last.flow_id}" rescue nil %>
          <div class="row">
            <div class="col-md-10 offset-md-1">
              <% if step.open? %>
                <%= form_with(model: step.movements.build, url: [@unit, step, step.movements.build], method: :post, local: true) do |form| %>
                  <%= form.collection_select :flow_id, step.movements.first.flow.children.all, :id, :title, {prompt: true}, {class: "form-control form-control-lg", required: true} %>
                  <br>
                  <%= form.fields_for :details do |detail| %>
                    <%= render "movements/actions/#{movements.last.flow_id}", detail: detail rescue nil %>
                    <% step.movements.first.flow.children.all.each do |flow| %>
                      <div class="step details-fields d-none" id="<%= flow.id %>">
                        <% flow.movement_field.each do |field| %>
                          <%= render "movements/forms/#{field.field_type}", field: field, detail: detail %>
                        <% end %> 
                      </div>
                    <% end %>
                    <div class="form-group">
                      <%= detail.label :remarks %>
                      <%= detail.text_area :remarks, {placeholder: "Remarks for this movement", class:"form-control"} %>
                    </div>
                  <% end %>
                  <%= form.submit "Update", :class => "btn btn-primary btn-lg" %>
                <% end %>                    
              <% else %>
              <% unless movements.last.details.blank? %>
                <hr>
                <h5>Details</h5>
                <% movements.last.details.each do |key, value| %>
                  <strong><%= key.humanize %>:</strong> <%= value %><br>
                <% end %>
              <% end %>
            <% end %>
            </div>
          </div>          
        </div>
      </article>
    <% end %>
  </div>
</div>




<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>